[package]
name = "stack-prs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stack-prs"
path = "src/main.rs"

[dependencies]
bpaf = "0.9"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.10"
log = "0.4"
fern = "0.7"
owo-colors = "4.2.3"
